export interface StdlibModule {
  preamble: string;
  internalName: string;
}

export const PRISM_STDLIB: Record<string, StdlibModule> = {
  "prism:strings": {
    internalName: "__prism_Strings",
    preamble: `const __prism_Strings = {
  trim: (s) => String(s).trim(),
  trimStart: (s) => String(s).trimStart(),
  trimEnd: (s) => String(s).trimEnd(),
  padStart: (s, n, c = " ") => String(s).padStart(n, c),
  padEnd: (s, n, c = " ") => String(s).padEnd(n, c),
  startsWith: (s, prefix) => String(s).startsWith(prefix),
  endsWith: (s, suffix) => String(s).endsWith(suffix),
  includes: (s, sub) => String(s).includes(sub),
  replace: (s, from, to) => String(s).replace(from, to),
  replaceAll: (s, from, to) => String(s).replaceAll(from, to),
  toUpper: (s) => String(s).toUpperCase(),
  toLower: (s) => String(s).toLowerCase(),
  split: (s, sep) => String(s).split(sep),
  repeat: (s, n) => String(s).repeat(n),
  charAt: (s, i) => String(s).charAt(i),
  indexOf: (s, sub) => String(s).indexOf(sub),
  lastIndexOf: (s, sub) => String(s).lastIndexOf(sub),
  slice: (s, start, end) => String(s).slice(start, end),
  length: (s) => String(s).length,
  isEmpty: (s) => String(s).length === 0,
  isBlank: (s) => String(s).trim().length === 0,
  reverse: (s) => String(s).split("").reverse().join(""),
  capitalize: (s) => { const str = String(s); return str.charAt(0).toUpperCase() + str.slice(1); },
  camelToSnake: (s) => String(s).replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, ""),
  snakeToCamel: (s) => String(s).replace(/_([a-z])/g, (_, c) => c.toUpperCase()),
};`,
  },

  "prism:arrays": {
    internalName: "__prism_Arrays",
    preamble: `const __prism_Arrays = {
  map: (arr, fn) => arr.map(fn),
  filter: (arr, fn) => arr.filter(fn),
  reduce: (arr, fn, init) => arr.reduce(fn, init),
  find: (arr, fn) => arr.find(fn) ?? null,
  findIndex: (arr, fn) => arr.findIndex(fn),
  includes: (arr, val) => arr.includes(val),
  indexOf: (arr, val) => arr.indexOf(val),
  slice: (arr, start, end) => arr.slice(start, end),
  push: (arr, val) => { arr.push(val); return arr; },
  pop: (arr) => arr.pop() ?? null,
  shift: (arr) => arr.shift() ?? null,
  unshift: (arr, val) => { arr.unshift(val); return arr; },
  reverse: (arr) => [...arr].reverse(),
  sort: (arr, fn) => [...arr].sort(fn),
  flat: (arr, depth = 1) => arr.flat(depth),
  flatMap: (arr, fn) => arr.flatMap(fn),
  forEach: (arr, fn) => arr.forEach(fn),
  some: (arr, fn) => arr.some(fn),
  every: (arr, fn) => arr.every(fn),
  join: (arr, sep = ",") => arr.join(sep),
  length: (arr) => arr.length,
  first: (arr) => arr[0] ?? null,
  last: (arr) => arr[arr.length - 1] ?? null,
  isEmpty: (arr) => arr.length === 0,
  unique: (arr) => [...new Set(arr)],
  uniqueBy: (arr, fn) => { const seen = new Set(); return arr.filter(v => { const k = fn(v); return seen.has(k) ? false : (seen.add(k), true); }); },
  zip: (a, b) => a.map((v, i) => [v, b[i]]),
  range: (start, end, step = 1) => { const r = []; for (let i = start; i < end; i += step) r.push(i); return r; },
  chunk: (arr, size) => { const r = []; for (let i = 0; i < arr.length; i += size) r.push(arr.slice(i, i + size)); return r; },
  groupBy: (arr, fn) => arr.reduce((acc, v) => { const k = fn(v); (acc[k] = acc[k] || []).push(v); return acc; }, {}),
  sum: (arr) => arr.reduce((a, b) => a + b, 0),
  min: (arr) => Math.min(...arr),
  max: (arr) => Math.max(...arr),
  flatten: (arr) => arr.flat(Infinity),
  compact: (arr) => arr.filter(Boolean),
  count: (arr, fn) => arr.filter(fn).length,
  take: (arr, n) => arr.slice(0, n),
  drop: (arr, n) => arr.slice(n),
};`,
  },

  "prism:json": {
    internalName: "__prism_Json",
    preamble: `const __prism_Json = {
  parse: (s) => { try { return JSON.parse(s); } catch { return null; } },
  stringify: (v, indent = 0) => JSON.stringify(v, null, indent),
  tryParse: (s) => { try { return { ok: true, value: JSON.parse(s) }; } catch (e) { return { ok: false, error: e.message }; } },
  isValid: (s) => { try { JSON.parse(s); return true; } catch { return false; } },
  clone: (v) => JSON.parse(JSON.stringify(v)),
  merge: (...objs) => Object.assign({}, ...objs),
};`,
  },

  "prism:console": {
    internalName: "__prism_Console",
    preamble: `const __prism_Console = {
  log: (...args) => console.log(...args),
  error: (...args) => console.error(...args),
  warn: (...args) => console.warn(...args),
  info: (...args) => console.info(...args),
  debug: (...args) => console.debug(...args),
  clear: () => console.clear(),
  time: (label) => console.time(label),
  timeEnd: (label) => console.timeEnd(label),
  table: (data) => console.table(data),
  group: (label) => console.group(label),
  groupEnd: () => console.groupEnd(),
  count: (label) => console.count(label),
  assert: (cond, msg) => console.assert(cond, msg),
};`,
  },

  "prism:env": {
    internalName: "__prism_Env",
    preamble: `const __prism_Env = {
  get: (key, fallback = "") => process.env[key] ?? fallback,
  set: (key, value) => { process.env[key] = value; },
  has: (key) => key in process.env,
  all: () => ({ ...process.env }),
  require: (key) => { const v = process.env[key]; if (v === undefined) throw new Error("Missing required env var: " + key); return v; },
};`,
  },

  "prism:fs": {
    internalName: "__prism_Fs",
    preamble: `import { readFileSync as __fs_readFileSync, writeFileSync as __fs_writeFileSync, existsSync as __fs_existsSync, mkdirSync as __fs_mkdirSync, readdirSync as __fs_readdirSync, unlinkSync as __fs_unlinkSync, statSync as __fs_statSync, appendFileSync as __fs_appendFileSync } from "fs";
import { resolve as __path_resolve, join as __path_join, dirname as __path_dirname, basename as __path_basename, extname as __path_extname } from "path";
const __prism_Fs = {
  read: (p) => __fs_readFileSync(p, "utf-8"),
  readBytes: (p) => __fs_readFileSync(p),
  write: (p, content) => __fs_writeFileSync(p, content, "utf-8"),
  append: (p, content) => __fs_appendFileSync(p, content, "utf-8"),
  exists: (p) => __fs_existsSync(p),
  mkdir: (p) => __fs_mkdirSync(p, { recursive: true }),
  list: (p) => __fs_readdirSync(p),
  remove: (p) => __fs_unlinkSync(p),
  stat: (p) => __fs_statSync(p),
  resolve: (...parts) => __path_resolve(...parts),
  join: (...parts) => __path_join(...parts),
  dirname: (p) => __path_dirname(p),
  basename: (p) => __path_basename(p),
  extname: (p) => __path_extname(p),
  isFile: (p) => { try { return __fs_statSync(p).isFile(); } catch { return false; } },
  isDir: (p) => { try { return __fs_statSync(p).isDirectory(); } catch { return false; } },
};`,
  },
};